# Generated by Django 5.0.1 on 2024-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DessertCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт торт',
                'verbose_name_plural': 'Десерты торты',
            },
        ),
        migrations.CreateModel(
            name='DessertIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт: Мороженое',
                'verbose_name_plural': 'Десерты: Мороженое',
            },
        ),
        migrations.CreateModel(
            name='DessertSnake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерт: Snake',
                'verbose_name_plural': 'Десерты: Snake',
            },
        ),
        migrations.CreateModel(
            name='FootBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Fast-Food: Бургер',
                'verbose_name_plural': 'Fast-Food: Бургеры',
            },
        ),
        migrations.CreateModel(
            name='FootPasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Fast-Food: Паста',
                'verbose_name_plural': 'Fast-Food: Пасты',
            },
        ),
        migrations.CreateModel(
            name='FootPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Fast-Food: Питца',
                'verbose_name_plural': 'Fast-Food: Питцы',
            },
        ),
        migrations.CreateModel(
            name='JuiceCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напитки:  Кофе',
                'verbose_name_plural': 'Напитки: Кофе',
            },
        ),
        migrations.CreateModel(
            name='JuiceFruitJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напитки: Фруктовый сок',
                'verbose_name_plural': 'Напитки: Фруктовый сок',
            },
        ),
        migrations.CreateModel(
            name='SetCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сет для пар',
                'verbose_name_plural': 'Сет для пары',
            },
        ),
        migrations.CreateModel(
            name='SetFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сет для семьи',
                'verbose_name_plural': 'Сет для семьи',
            },
        ),
        migrations.CreateModel(
            name='SetIndivudal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SetFamily_image', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.CharField(max_length=255, verbose_name='Прошлая цена')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сет для индивидуальных',
                'verbose_name_plural': 'Сет для индивидуальных',
            },
        ),
    ]
