# Generated by Django 5.0.1 on 2024-01-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions2', models.TextField(verbose_name='Описание')),
                ('customers', models.CharField(max_length=255, verbose_name='Всего клиентов')),
                ('qutlet', models.CharField(max_length=255, verbose_name='Всемирная торговая точка')),
                ('satisfaction', models.CharField(max_length=255, verbose_name='Удовлетворение')),
            ],
            options={
                'verbose_name': 'Настройкка о нас',
                'verbose_name_plural': 'Настройки о нас',
            },
        ),
        migrations.AlterModelOptions(
            name='begin',
            options={'verbose_name': 'Настройка начало', 'verbose_name_plural': 'Настройки начало'},
        ),
    ]
