# Generated by Django 5.0.1 on 2024-01-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_about_alter_begin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Настройкка котегории',
                'verbose_name_plural': 'Настройки котегории',
            },
        ),
    ]
