# Generated by Django 5.0.1 on 2024-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('price_dicount', models.CharField(max_length=255, verbose_name='Цена без скидки')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Настройка предложений',
                'verbose_name_plural': 'Настройки предложений',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Настройка продукты', 'verbose_name_plural': 'Настройки продуктов'},
        ),
    ]
