# Generated by Django 5.0.1 on 2024-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_offer_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Отыв')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Настройка Отзыва',
                'verbose_name_plural': 'Настройки Отзывов',
            },
        ),
    ]
