# Generated by Django 5.0.1 on 2024-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='descriptions',
            field=models.TextField(verbose_name='Отыв'),
        ),
    ]
