# Generated by Django 5.0.1 on 2024-01-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('mini_descriptions', models.CharField(max_length=255, verbose_name='Мини описание 1')),
                ('mini_descriptions3', models.CharField(max_length=255, verbose_name='Мини описание 1')),
                ('mini_descriptions2', models.CharField(max_length=255, verbose_name='Мини описание 1')),
            ],
            options={
                'verbose_name': 'Настройка страницы о нас',
                'verbose_name_plural': 'Настройки страницы о нас',
            },
        ),
    ]
