# Generated by Django 5.0.1 on 2024-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='mini_descriptions4',
            field=models.CharField(default=1, max_length=255, verbose_name='Мини описание 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about_page',
            name='mini_descriptions2',
            field=models.CharField(max_length=255, verbose_name='Мини описание 2'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='mini_descriptions3',
            field=models.CharField(max_length=255, verbose_name='Мини описание 3'),
        ),
    ]
