# Generated by Django 5.0.1 on 2024-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Навзание')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('price_discount', models.CharField(max_length=255, verbose_name='Цена без скидки')),
            ],
            options={
                'verbose_name': 'Настройка Магазина',
                'verbose_name_plural': 'Настройки Магазина',
            },
        ),
    ]
