# Generated by Django 5.0.1 on 2024-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
