# Generated by Django 5.0.1 on 2024-01-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0016_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
