# Generated by Django 5.0.1 on 2024-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='discriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='discriptions_mini',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
