# Generated by Django 5.0.1 on 2024-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_shops_discriptions_shops_discriptions_mini'),
    ]

    operations = [
        migrations.CreateModel(
            name='FructJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='fruct_juice/', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Фруктовый коктель',
                'verbose_name_plural': 'Фруктовые коктели',
            },
        ),
        migrations.CreateModel(
            name='IceCreame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='ice_creame', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='MilkShake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='milk_shake', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Молочный коктель',
                'verbose_name_plural': 'Молочные коктели',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Настройка новостей в Index', 'verbose_name_plural': 'Настройки новостей index'},
        ),
    ]
