# Generated by Django 5.0.1 on 2024-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='logo',
            new_name='logo1',
        ),
        migrations.AddField(
            model_name='settings',
            name='logo2',
            field=models.ImageField(default=1, upload_to='logo_image', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
