# Generated by Django 5.0.1 on 2024-01-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_logo_settings_logo1_settings_logo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='logo1',
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_image', verbose_name='Логотип1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo2',
            field=models.ImageField(upload_to='logo_image', verbose_name='Логотип2'),
        ),
    ]
